### ISSUE TITLE
[Docs]: Add Copy to Clipboard Button for the source code

### ISSUE THREAD

**Issue by pravintargaryen** [remix-run/react-router-website#114] opened 2024-07-08 16:55 UTC
### Describe what's incorrect/missing in the documentation

While working on the react-router tutorial, I was astonished to find that there is no copy to clipboard button for the code examples probably encouraging devs to write code on their own

![1](https://github.com/remix-run/react-router/assets/96950453/00e61395-07b7-4695-a1d4-f3e7f1790236)

**Comment by timdorr** [comment] 2024-07-08 21:45
Duplicate of #110

**Closed by timdorr** 2024-07-08 21:45 UTC
